# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

grad_ls_loss <- function(x, y, param, p) {
    .Call(`_cbSCRIP_grad_ls_loss`, x, y, param, p)
}

grad_logistic_loss <- function(x, y, param, p) {
    .Call(`_cbSCRIP_grad_logistic_loss`, x, y, param, p)
}

scalar_scad_prox <- function(val, lambda, a) {
    .Call(`_cbSCRIP_scalar_scad_prox`, val, lambda, a)
}

proximalSCAD <- function(U, lam1, a_scad = 3.7, pos = FALSE) {
    invisible(.Call(`_cbSCRIP_proximalSCAD`, U, lam1, a_scad, pos))
}

MultinomLogistic <- function(X, Y, offset, K, reg_p, penalty, regul, transpose, grp_id, etaG, grp, grpV, own_var, N_own_var, lam1, lam2, lam3, learning_rate, tolerance, niter_inner, maxit, ncores, save_history = FALSE, verbose = FALSE, param_start = NULL) {
    .Call(`_cbSCRIP_MultinomLogistic`, X, Y, offset, K, reg_p, penalty, regul, transpose, grp_id, etaG, grp, grpV, own_var, N_own_var, lam1, lam2, lam3, learning_rate, tolerance, niter_inner, maxit, ncores, save_history, verbose, param_start)
}

MultinomLogisticSAGA <- function(X, Y, offset, K, reg_p, penalty, regul, transpose, grp_id, etaG, grp, grpV, own_var, N_own_var, lam1, lam2, lam3, tolerance = 1e-6, maxit = 500L, ncores = 1L, verbose = FALSE, pos = FALSE, param_start = NULL) {
    .Call(`_cbSCRIP_MultinomLogisticSAGA`, X, Y, offset, K, reg_p, penalty, regul, transpose, grp_id, etaG, grp, grpV, own_var, N_own_var, lam1, lam2, lam3, tolerance, maxit, ncores, verbose, pos, param_start)
}

accelerated_stochastic_optimizer <- function(X, Y, offset, K, estimator_type, tolerance, maxit, niter_inner, batch_size, param_start, verbose, reg_p, penalty, regul, transpose, grp_id, etaG, grp, grpV, own_var, N_own_var, lam1, lam2, lam3, pos, ncores) {
    .Call(`_cbSCRIP_accelerated_stochastic_optimizer`, X, Y, offset, K, estimator_type, tolerance, maxit, niter_inner, batch_size, param_start, verbose, reg_p, penalty, regul, transpose, grp_id, etaG, grp, grpV, own_var, N_own_var, lam1, lam2, lam3, pos, ncores)
}

MultinomLogisticAcc <- function(X, Y, offset, K, reg_p, penalty, regul, transpose, grp_id, etaG, grp, grpV, own_var, N_own_var, lam1, lam2, lam3, c_factor, v_factor, tolerance = 1e-3, niter_inner = 100L, maxit = 500L, ncores = 1L, save_history = FALSE, verbose = FALSE, pos = FALSE, batch_size = 64L, param_start = NULL) {
    .Call(`_cbSCRIP_MultinomLogisticAcc`, X, Y, offset, K, reg_p, penalty, regul, transpose, grp_id, etaG, grp, grpV, own_var, N_own_var, lam1, lam2, lam3, c_factor, v_factor, tolerance, niter_inner, maxit, ncores, save_history, verbose, pos, batch_size, param_start)
}

